#Configuation for robot odometry EKF
#
frequency: 50
two_d_mode: true
predict_to_current_time: true

odom0: dingo_velocity_controller/odom
odom0_config: [true, true, false,
               false, false, true,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: true
odom0_relative: true
imu0: imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
imu0_differential: true
odom_frame: $(arg robot_name)/odom
base_link_frame: $(arg robot_name)/base_link
world_frame: $(arg robot_name)/odom
